name: 'Migration template'

on:
  push:
    branches:
      - develop
      - staging
      - main

jobs:
  migration-template:
    runs-on: ubuntu-latest
    environment:
      name: |-
        ${{
          github.ref_name == 'main' && 'production' ||
          github.ref_name == 'staging' && 'staging' ||
          'development'
        }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup and cache Node
        uses: ./.github/actions/setup-node

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Create .env
        run: |
          touch .env
          echo SG_API_KEY=${{ secrets.SG_API_KEY }} >> .env

      - name: Run migration
        run: |
          node migration.js
